### ISSUE TITLE
request: checksum check for zrif string

### ISSUE THREAD

**Issue by tomazzz369** [VitaSmith/VitaDB#1]
would be useful in case someone will post invalid zrif string. same as in pkg2zip

https://github.com/mmozeiko/pkg2zip/blob/master/pkg2zip_zrif.c

if (mz_adler32(MZ_ADLER32_INIT, out, dlen) != get32be(in + slen))
{
    sys_error("ERROR: zRIF is corrupted, wrong checksum\n");
}

regards

**Comment by VitaSmith** [comment]
Well, we're picking the zRIFs from NPS and if you go through an import/export of zRIFs you'll filter out the invalid ones anyway.

If someone sends a pull request, I'll apply it, but otherwise...
